### ISSUE TITLE
Dependency should be on "identity" not the official "git+ssh://...." url

### ISSUE THREAD

**Issue by timcleaver-techconnect** [Azure-Samples/ms-identity-python-webapp-django#3]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> clone repo
> follow instructions
> python manage.py migrate

ModuleNotFoundError: No module named 'identity'

### Any log messages given by the failure
>

### Expected/desired behavior
> requirements.txt should contain "identity[django]" and not ms_identity_python[django] @ git+https://github.com/azure-samples/ms-identity-python@0.8
> or the code should be updated so that the requirements.txt as is works. 

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by rayluo** [comment]
> requirements.txt should contain "identity[django]" and not `ms_identity_python[django] @ git+https://github.com/azure-samples/ms-identity-python@0.8`

They were supposed to be interchangeable, but we ran into a regression. This repo received a new change recently to fix it. Would you please test it again?
